export const reactjs = [
  {
    title: "5th Grade Coordinates/Volume",
    grade: "5th grade",
    questionsCount: 10,
    playsCount: 100,
    color: "/6.png",
  },
  {
    title: "Properties of quadrilaterals",
    grade: "6th grade",
    questionsCount: 10,
    playsCount: 100,
    color: "/2.png",
  },
  {
    title: "Common Monomial Factor",
    grade: "7th grade",
    questionsCount: 10,
    playsCount: 100,
    color: "/3.png",
  },
  {
    title: "Central America and the Caribbean",
    grade: "8th grade",
    questionsCount: 10,
    playsCount: 100,
    color: "/1.png",
  },
  {
    title: "React js",
    grade: "High School",
    questionsCount: 10,
    playsCount: 100,
    color: "/2.png",
  },
  {
    title: "El Alfabeto",
    grade: "Elementary",
    questionsCount: 10,
    playsCount: 100,
    color: "/2.png",
  },
];

export const nodejs = [
  {
    title: "5th Grade Coordinates/Volume",
    grade: "5th grade",
    questionsCount: 10,
    playsCount: 100,
    color: "/6.png",
  },
  {
    title: "Properties of quadrilaterals",
    grade: "6th grade",
    questionsCount: 10,
    playsCount: 100,
    color: "/2.png",
  },
  {
    title: "Common Monomial Factor",
    grade: "7th grade",
    questionsCount: 10,
    playsCount: 100,
    color: "/3.png",
  },
  {
    title: "Central America and the Caribbean",
    grade: "8th grade",
    questionsCount: 10,
    playsCount: 100,
    color: "/1.png",
  },
  {
    title: "React js",
    grade: "High School",
    questionsCount: 10,
    playsCount: 100,
    color: "/2.png",
  },
  {
    title: "El Alfabeto",
    grade: "Elementary",
    questionsCount: 10,
    playsCount: 100,
    color: "/2.png",
  },
  {
    title: "Node.js",
    grade: "Professional",
    questionsCount: 10,
    playsCount: 100,
    color: "/4.png",
  },
];
